### ISSUE TITLE
Job logs area is so wide

### ISSUE THREAD

**Issue by ibalat** [mshade/kronic#57]
Hi, logs area is so wide and spills out. Maybe it can be in scrolling area. Please can you fix it?

![image](https://github.com/mshade/kronic/assets/146727489/7965ac2d-c5f2-46bc-855a-f70e87828785)

**Comment by mshade** [comment]
I'll take a look at adding a container for this!

**Comment by mshade** [comment]
Thanks for the report @ibalat - this is fixed in `main` and I'll create a release for it soon.

If you'd like to test before that release is out, set the image tag to `sha-bcee26b` to grab the latest build from main, which also contains some performance enhancements.

**Comment by ibalat** [comment]
Thank yo so much. I'll test it and wait the release 🎉
